---
# Infrastructure
# - Defines the vCenter / vSphere environment
deploy_vsphere_vcenter: 'photon-machine.contagion.local'
deploy_vsphere_user: 'administrator@vsphere.local'
deploy_vsphere_password: ''
deploy_vsphere_datacenter: 'Datacenter'
deploy_vsphere_folder: 'deployments/CentOS'
deploy_vsphere_cluster: ''
deploy_vsphere_resourcepool: ''

# Guest
# - Describes virtual machine common options
guest_network: 'VM Network'
guest_netmask: ''
guest_gateway: ''
guest_dns_server: '192.168.1.1'
guest_domain_name: 'contagion.local'
guest_id: ''
guest_memory: '4096'
guest_vcpu: '2'
#guest_template: ''
guest_wait_for_ip_address: 'yes'
guest_state: 'poweredon'

# Misc config
machine_group: 'machines'
machine_user: 'user'
machine_initial_user: 'root'
machine_initial_password: ''

