---
- hosts: machines
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
          #- name: Reboot
      #reboot:
    - name: Install nginx
      yum:
        name: nginx
        state: latest
    - name: Ping
      ping:
        data: gogo
