---
- name: Gather info about VM
  community.vmware.vmware_guest_info:
    hostname: "{{ deploy_vsphere_vcenter }}"
    username: "{{ deploy_vsphere_user }}"
    password: "{{ deploy_vsphere_password }}"
    datacenter: "{{ deploy_vsphere_datacenter }}"
    validate_certs: no
    folder: "{{ deploy_vsphere_folder }}"
    name: "{{ item }}"
  delegate_to: localhost
  register: facts
  with_items:
    - "{{ vm_names }}"

- name: Register IP in inventory
  add_host:
    name: "{{ item.item }}"
    ansible_ssh_host: "{{ item.instance.ipv4 }}"
    ansible_ssh_user: "{{ machine_initial_user }}"
    ansible_ssh_pass: "{{ machine_initial_password }}"
  with_items:
    - "{{ facts.results }}"

- name: Test VM
  ping:
    data: peekaboo
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups[machine_group] }}"
  become: yes

- name: Create ansible user
  user:
    name: "{{ machine_user }}"
    groups: wheel
    create_home: yes
    generate_ssh_key: yes
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups[machine_group] }}"
  become: yes

- name: Upload new sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: "0440"
    owner: root
    group: root
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups[machine_group] }}"
  become: yes

- name: Upload authorized_keys
  copy:
    src: authorized_keys
    dest: /home/{{ machine_user }}/.ssh/authorized_keys
    mode: "0600"
    owner: "{{ machine_user }}"
    group: wheel
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups[machine_group] }}"
  become: yes
